# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0002_auto_20170609_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganiserHandover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handedoveron', models.DateTimeField(auto_now_add=True, null=True)),
                ('handedoverfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_log.organiser')),
                ('handedoverto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handed_over_to', to='reg_log.organiser')),
            ],
        ),
    ]
