# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0003_organiserhandover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiserhandover',
            name='handedoverto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organiser_handed_over_to', to='reg_log.organiser'),
        ),
    ]
