# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reg_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CSV_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Depertment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DeptOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_log.college')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRAINING.Depertment')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('with_exam', models.BooleanField(default=True)),
                ('available_for_training', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRAINING.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MasterBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_log.college')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('csv', models.ManyToManyField(to='TRAINING.CSV_list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_log.college')),
                ('depertment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRAINING.Depertment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRAINING.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('csv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRAINING.CSV_list')),
                ('depertment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRAINING.Depertment')),
                ('foss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRAINING.Foss')),
                ('handedoverto', models.ManyToManyField(blank=True, related_name='training_handed_over_to', to='reg_log.organiser')),
                ('this_organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_log.organiser')),
            ],
        ),
        migrations.AddField(
            model_name='csv_list',
            name='masterbatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRAINING.MasterBatch'),
        ),
    ]
