# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRAINING', '0005_auto_20170610_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='csv',
        ),
        migrations.AddField(
            model_name='student',
            name='csv',
            field=models.ManyToManyField(to='TRAINING.CSV_list'),
        ),
    ]
