# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRAINING', '0006_auto_20170612_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depertment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRAINING.Depertment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRAINING.Student')),
            ],
        ),
    ]
