# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0004_auto_20170706_1006'),
        ('TRAINING', '0007_deptstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='organiser',
            new_name='this_organiser',
        ),
        migrations.AddField(
            model_name='training',
            name='handedoverto',
            field=models.ManyToManyField(blank=True, related_name='training_handed_over_to', to='reg_log.organiser'),
        ),
    ]
