# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRAINING', '0008_auto_20170706_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptorg',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
