# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRAINING', '0009_deptorg_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deptorg',
            name='status',
        ),
    ]
